# Generated by Django 3.2.3 on 2022-01-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_listing',
            name='geom_long',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
