# Generated by Django 3.2.3 on 2022-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_listing_geom_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_listing',
            name='price_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
