# Generated by Django 3.2.3 on 2022-01-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_rental_listing_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_listing',
            old_name='city',
            new_name='region',
        ),
    ]
