# Generated by Django 3.2.3 on 2022-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_rename_city_rental_listing_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listing',
            name='region',
            field=models.CharField(blank=True, choices=[('HT', 'Mutare'), ('HRE', 'Harare'), ('CHY', 'Chinhoyi')], max_length=200),
        ),
    ]
