# Generated by Django 3.2.3 on 2022-01-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rental_listing_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_listing',
            old_name='region',
            new_name='city',
        ),
    ]
