# Generated by Django 3.2.3 on 2022-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_rename_region_rental_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listing',
            name='city',
            field=models.CharField(blank=True, choices=[('MT', 'Mutare'), ('HRE', 'Harare'), ('CHY', 'Chinhoyi')], max_length=200),
        ),
    ]
