# Generated by Django 3.2.3 on 2022-01-08 08:36

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_rental_listing_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='geom_lat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='geom_long',
            field=models.FloatField(default=0, null=True),
        ),
    ]
