# Generated by Django 3.2.3 on 2022-01-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_city'),
        ('rental', '0012_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=0, null=True)),
                ('rejected', models.BooleanField(default=0, null=True)),
                ('waiting_list', models.BooleanField(default=0, null=True)),
                ('date_of_booking', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='city',
            field=models.CharField(blank=True, choices=[('Mutare', 'Mutare'), ('Harare', 'Harare'), ('Gweru', 'Gweru'), ('Masvingo', 'Masvingo'), ('Chinhoyi', 'Chinhoyi'), ('Bulawayo', 'Bulawayo'), ('Zvishavane', 'Zvishavane')], max_length=200),
        ),
        migrations.CreateModel(
            name='BookingPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_payment_attached', models.BooleanField(default=0, null=True)),
                ('file', models.FileField(default=0, null=True, upload_to='')),
                ('amount', models.FloatField(null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.rental_listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
