# Generated by Django 3.2.3 on 2022-01-09 17:34

from django.db import migrations, models
import rental.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_booking_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpay',
            name='file',
            field=models.FileField(null=True, upload_to=rental.models.user_directory_path),
        ),
    ]
