# Generated by Django 3.2.10 on 2022-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_bookingpay_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_listing',
            name='preference',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], max_length=200),
        ),
    ]
