# Generated by Django 3.2.10 on 2022-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_auto_20220111_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_listing',
            name='pets_allowed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
