# Generated by Django 3.2.10 on 2022-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_rental_listing_pets_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
