# Generated by Django 3.2.10 on 2022-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listing',
            name='pets_allowed',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
