# Generated by Django 3.2.3 on 2022-01-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
