# Generated by Django 3.2.3 on 2022-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220108_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Mutare', 'Mutare'), ('Harare', 'Harare'), ('Gweru', 'Gweru'), ('Masvingo', 'Masvingo'), ('Chinhoyi', 'Chinhoyi'), ('Bulawayo', 'Bulawayo'), ('Zvishavane', 'Zvishavane')], max_length=200),
        ),
    ]
